spring:
  application:
    name: article-summarizer
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

rapidapi:
  key: ${RAPIDAPI_KEY}
  host: article-extractor-and-summarizer.p.rapidapi.com
  base-url: https://article-extractor-and-summarizer.p.rapidapi.com

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs

server:
  port: 8081